export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    label: 'For early-stage sales teams.',
    monthlyPrice: 1299,
    yearlyPrice: 999,
    cta: 'Start Free Trial',
    href: '/user/register',
    highlighted: false,
    enterprise: false,
    features: [
      '2 team members',
      'CRM dashboard',
      'Lead pipeline',
      'WhatsApp inbox',
      'Meta Ads integration',
      'Website forms',
      'Lead assignment',
      'Tasks & reminders',
      'Basic automations',
      'Basic reports',
      '1 WhatsApp number',
      'Mobile responsive dashboard',
    ],
    limits: ['2,000 contacts', '500 automation actions/month'],
  },
  {
    id: 'growth',
    name: 'Growth',
    label: 'For teams that need speed and accountability.',
    monthlyPrice: 3999,
    yearlyPrice: 2999,
    badge: 'Most Popular',
    cta: 'Start 14-Day Trial',
    href: '/user/register',
    highlighted: true,
    enterprise: false,
    features: [
      'Everything in Starter, plus:',
      '10 team members',
      'Sequences',
      'Team inbox',
      'Round-robin assignment',
      'SLA reminders',
      'Call recovery',
      'Advanced automations',
      'Google Ads integration',
      'Razorpay integration',
      'Revenue analytics',
      'Team performance tracking',
      'Multiple pipelines',
      'Export reports',
      'Workflow templates',
      'Role permissions',
    ],
    limits: ['25,000 contacts', '10,000 automation actions/month'],
  },
  {
    id: 'scale',
    name: 'Scale',
    label: 'For high-performance operations.',
    monthlyPrice: 9999,
    yearlyPrice: 7999,
    cta: 'Book Demo',
    href: '/contact',
    highlighted: false,
    enterprise: false,
    features: [
      'Everything in Growth, plus:',
      'Unlimited team members',
      'AI WhatsApp assistant',
      'AI reply suggestions',
      'AI lead qualification',
      'Multi-workspace support',
      'Multi-number WhatsApp',
      'API access',
      'Webhooks',
      'Funnel intelligence',
      'Custom dashboards',
      'Audit logs',
      'SSO login',
      'Advanced permissions',
      'SLA monitoring',
      'Priority support',
    ],
    limits: ['100,000 contacts', '100,000 automation actions/month'],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    label: 'Enterprise-grade revenue infrastructure.',
    monthlyPrice: null,
    yearlyPrice: null,
    cta: 'Contact Sales',
    href: '/contact',
    highlighted: false,
    enterprise: true,
    features: [
      'Everything unlimited',
      'Dedicated infrastructure',
      'White-label mode',
      'Agency mode',
      'AI calling system',
      'Salesforce sync',
      'ERP integrations',
      'Dedicated account manager',
      'Compliance support',
      'Security review',
      'Multi-region deployment',
      'Internal workflow consulting',
    ],
    limits: ['Custom limits', 'Dedicated SLA'],
  },
];

export const ADDONS = [
  {
    name: 'AI Calling Assistant',
    price: '2,999',
    period: '/ month',
    bullets: ['AI voice follow-ups', 'Missed call recovery', 'Automated reminders'],
  },
  {
    name: 'Extra WhatsApp Number',
    price: '999',
    period: '/ number / month',
    bullets: ['Additional business line', 'Separate routing rules', 'Team assignment per number'],
  },
  {
    name: 'Additional Team Member',
    price: '299',
    period: '/ user / month',
    bullets: ['Add seats beyond plan', 'Full CRM access', 'Role-based permissions'],
  },
  {
    name: 'Advanced Analytics Pack',
    price: '1,999',
    period: '/ month',
    bullets: ['Funnel intelligence', 'Conversion heatmaps', 'Sales forecasting'],
  },
  {
    name: 'API & Webhook Upgrade',
    price: '2,499',
    period: '/ month',
    bullets: ['Higher API limits', 'Advanced integrations', 'Custom event streams'],
  },
  {
    name: 'Dedicated Onboarding',
    price: '9,999',
    period: ' one-time',
    bullets: ['Setup support', 'Workflow migration', 'Team training'],
  },
];

export const COMPARISON_ROWS = [
  { feature: 'Instant lead response', lfg: true, crm: 'Manual', manual: false },
  { feature: 'WhatsApp automation', lfg: true, crm: 'Add-on', manual: false },
  { feature: 'Team accountability', lfg: true, crm: 'Limited', manual: false },
  { feature: 'Auto follow-ups', lfg: true, crm: 'Partial', manual: false },
  { feature: 'Revenue visibility', lfg: true, crm: 'Reports only', manual: false },
  { feature: 'SLA tracking', lfg: true, crm: 'Optional', manual: false },
  { feature: 'AI assistance', lfg: true, crm: 'Rare', manual: false },
  { feature: 'Call recovery', lfg: true, crm: 'No', manual: false },
  { feature: 'Workflow automation', lfg: true, crm: 'Complex setup', manual: false },
];

export const USAGE_LIMITS = [
  { label: 'Contacts', starter: 2000, growth: 25000, scale: 100000, enterprise: 'Unlimited' },
  { label: 'Automation actions / mo', starter: 500, growth: 10000, scale: 100000, enterprise: 'Unlimited' },
  { label: 'WhatsApp conversations', starter: 2000, growth: 10000, scale: 50000, enterprise: 'Unlimited' },
  { label: 'API requests / mo', starter: 5000, growth: 50000, scale: 250000, enterprise: 'Custom' },
  { label: 'Storage', starter: '5 GB', growth: '25 GB', scale: '100 GB', enterprise: 'Custom' },
  { label: 'Team seats', starter: 2, growth: 10, scale: 'Unlimited', enterprise: 'Unlimited' },
];

export const ONBOARDING_STEPS = [
  { step: '1', title: 'Connect WhatsApp', desc: 'Link your official WhatsApp Business API in minutes.' },
  { step: '2', title: 'Import leads', desc: 'Sync Meta ads, forms, spreadsheets, or your existing CRM.' },
  { step: '3', title: 'Setup automations', desc: 'Deploy follow-up sequences, routing, and SLA rules.' },
  { step: '4', title: 'Invite team', desc: 'Assign roles, pipelines, and accountability dashboards.' },
  { step: '5', title: 'Go live', desc: 'Start converting with real-time revenue visibility.' },
];

export const PRICING_FAQ = [
  { q: 'Do I need Meta API?', a: 'Yes, for official WhatsApp automation at scale. We guide you through Meta Business verification and API setup during onboarding — typically within one business day.' },
  { q: 'Can I migrate from Zoho?', a: 'Yes. Import contacts, deals, and activity history. Our onboarding team helps map pipelines and automations so you do not lose momentum during migration.' },
  { q: 'Is onboarding included?', a: 'Self-serve onboarding is included on all plans. Growth and above include guided setup. Dedicated onboarding is available as a one-time add-on.' },
  { q: 'Can I use multiple WhatsApp numbers?', a: 'Starter includes one number. Scale and Enterprise support multi-number routing. Additional numbers are available as add-ons on any plan.' },
  { q: 'Does LeadForGrow support agencies?', a: 'Yes. Enterprise includes agency mode and white-label deployment. Manage multiple client workspaces with consolidated reporting and billing.' },
  { q: 'Can I upgrade anytime?', a: 'Upgrade instantly from your billing settings. Downgrades apply at the next billing cycle. No lock-in contracts on standard plans.' },
  { q: 'Is AI calling available?', a: 'AI Calling Assistant is available as an add-on on Growth+, and included in Enterprise custom packages.' },
  { q: 'What happens after trial ends?', a: 'Your data is preserved for 14 days. Choose a plan to continue, or export your leads and conversation history before the grace period ends.' },
];

export const TRUST_BADGES = [
  'Official WhatsApp API',
  'Setup in 1 day',
  'Used by growing Indian sales teams',
];

export function formatINR(amount) {
  if (amount == null) return 'Custom';
  return `₹${amount.toLocaleString('en-IN')}`;
}
