/** Product page content — each uses a distinct layout variant */

export const PRODUCT_PAGES = {
  crm: {
    layout: 'split-screenshot',
    meta: { title: 'CRM & Sales Pipeline | LeadForGrow', description: 'Visual pipeline CRM built for speed. Track leads, assign owners, close deals.' },
    overline: 'CRM',
    headline: 'Every lead in one place. Zero spreadsheet chaos.',
    subheadline: 'A pipeline your team will actually use — visual stages, instant assignment, and full conversation history on every contact.',
    accent: 'emerald',
    features: [
      { title: 'Visual kanban pipeline', desc: 'Drag leads between stages. See bottlenecks at a glance.' },
      { title: 'Lead scoring & tags', desc: 'Prioritize hot leads automatically with AI-assisted scoring.' },
      { title: 'Team assignment', desc: 'Round-robin or manual — every lead gets an owner in seconds.' },
      { title: 'Activity timeline', desc: 'Calls, emails, WhatsApp, notes — one timeline per lead.' },
    ],
    useCases: ['Sales teams closing 50+ leads/month', 'Agencies managing multiple client pipelines', 'Owner-operators who need clarity without complexity'],
    faq: [
      { q: 'How is this different from Salesforce?', a: 'We built for speed, not enterprise complexity. Setup takes minutes, not months.' },
      { q: 'Can I import from Excel?', a: 'Yes — CSV import with field mapping in one click.' },
    ],
    cta: 'Start managing leads',
  },
  automation: {
    layout: 'flow-diagram',
    meta: { title: 'Automation Platform | LeadForGrow', description: 'No-code workflows for WhatsApp, email, CRM actions, and AI — without writing code.' },
    overline: 'Automation',
    headline: 'Automate follow-ups before your competitor calls back.',
    subheadline: 'Visual workflow builder with triggers, conditions, delays, and multi-channel actions — built on top of your CRM and inbox.',
    accent: 'teal',
    features: [
      { title: 'Visual workflow builder', desc: 'Drag-and-drop sequences with 35+ triggers and actions.' },
      { title: 'WhatsApp & email sequences', desc: 'Multi-step nurture across channels with smart delays.' },
      { title: 'Broadcast campaigns', desc: 'Send targeted WhatsApp and email campaigns to segments.' },
      { title: 'AI-powered steps', desc: 'Qualify leads, generate replies, and score automatically.' },
    ],
    useCases: ['Instant lead acknowledgement', 'Missed call recovery', 'Payment and demo reminders'],
    faq: [
      { q: 'Do I need to code?', a: 'No. Every workflow is built visually in the sequence builder.' },
      { q: 'Does it work with WhatsApp Business API?', a: 'Yes — native Meta Cloud API and Interakt integration.' },
    ],
    cta: 'Build your first workflow',
  },
  ai: {
    layout: 'center-glow',
    meta: { title: 'AI Assistant | LeadForGrow', description: 'AI reply assistant, lead qualification, and knowledge base for your business.' },
    overline: 'AI Platform',
    headline: 'AI that knows your business — not generic ChatGPT.',
    subheadline: 'Trained on your products, FAQs, and past conversations. Reply faster, qualify smarter, escalate when it matters.',
    accent: 'cyan',
    features: [
      { title: 'AI reply assistant', desc: 'Draft WhatsApp and email replies grounded in your knowledge base.' },
      { title: 'Lead qualification', desc: 'Automatic scoring based on intent, budget signals, and engagement.' },
      { title: 'Knowledge base', desc: 'Upload docs, URLs, and FAQs — AI retrieves the right answer.' },
      { title: 'Copilot for agents', desc: 'Suggest next actions while your team works the inbox.' },
    ],
    useCases: ['High-volume WhatsApp enquiries', 'After-hours lead response', 'Consistent brand voice across team'],
    faq: [
      { q: 'Is my data used to train models?', a: 'No. Your knowledge stays isolated to your workspace.' },
      { q: 'Can AI hand off to humans?', a: 'Yes — escalation rules trigger when confidence is low or customer requests it.' },
    ],
    cta: 'Try AI assistant',
  },
  'unified-inbox': {
    layout: 'channel-grid',
    meta: { title: 'Unified Inbox | LeadForGrow', description: 'WhatsApp, Instagram, email, and website chat in one inbox.' },
    overline: 'Unified Inbox',
    headline: 'One inbox for every channel your customers use.',
    subheadline: 'Stop switching between WhatsApp Web, Gmail, and Instagram DMs. Respond from one place with full context.',
    accent: 'violet',
    features: [
      { title: 'WhatsApp Business', desc: 'Official API integration with templates and media.' },
      { title: 'Email sync', desc: 'Connect Gmail or SMTP — threads linked to leads automatically.' },
      { title: 'Instagram DMs', desc: 'Meta integration for social selling teams.' },
      { title: 'Team assignment', desc: 'Route conversations by skill, load, or round-robin.' },
    ],
    useCases: ['Sales teams on WhatsApp-first markets', 'Support teams handling email + chat', 'Agencies managing client inboxes'],
    faq: [
      { q: 'Can multiple team members use one WhatsApp number?', a: 'Yes — shared inbox with assignment and internal notes.' },
    ],
    cta: 'Unify your inbox',
  },
  integrations: {
    layout: 'logo-wall',
    meta: { title: 'Integrations | LeadForGrow', description: 'Connect WhatsApp, Meta, Gmail, Stripe, Razorpay, and more.' },
    overline: 'Integrations',
    headline: 'Connect the tools you already use.',
    subheadline: 'Native integrations for the channels and payment systems your business runs on — no Zapier required for core workflows.',
    accent: 'indigo',
    features: [
      { title: 'WhatsApp Cloud API', desc: 'Meta-approved templates and webhook events.' },
      { title: 'Meta Lead Ads', desc: 'Instant lead sync from Facebook and Instagram ads.' },
      { title: 'Email providers', desc: 'Gmail, Outlook, and custom SMTP.' },
      { title: 'Payments', desc: 'Stripe and Razorpay for invoice and payment triggers.' },
    ],
    useCases: ['Meta ad lead capture', 'Payment confirmation automations', 'Calendar booking sync'],
    faq: [
      { q: 'Do you have an API?', a: 'Yes — REST API for leads, webhooks, and custom integrations. See API docs.' },
    ],
    cta: 'View all integrations',
  },
  pricing: {
    layout: 'pricing-redirect',
    meta: { title: 'Pricing | LeadForGrow', description: 'Simple, transparent pricing for businesses and agencies.' },
    redirect: '/pricing',
  },
};

export const SOLUTION_PAGES = {
  startups: {
    layout: 'story-vertical',
    meta: { title: 'LeadForGrow for Startups', description: 'Move fast without hiring a sales ops team.' },
    overline: 'Startups',
    headline: 'Ship revenue ops before you ship v2.',
    subheadline: 'Capture leads from your landing page, respond in minutes, and automate follow-up — all before you hire your first SDR.',
    stats: [{ value: '10 min', label: 'Average setup' }, { value: '3x', label: 'Faster response' }, { value: '₹0', label: 'Extra tools needed' }],
    features: ['Free trial, no credit card', 'WhatsApp-first for Indian market', 'Scales from solo founder to 20-person team'],
  },
  agencies: {
    layout: 'multi-client',
    meta: { title: 'LeadForGrow for Agencies', description: 'White-label CRM and automation for client management.' },
    overline: 'Agencies',
    headline: 'One platform. Every client. Your brand.',
    subheadline: 'Manage multiple client workspaces, white-label the experience, and prove ROI with per-client analytics.',
    stats: [{ value: '∞', label: 'Client workspaces' }, { value: '100%', label: 'White-label ready' }, { value: '24h', label: 'Client onboarding' }],
    features: ['Separate pipelines per client', 'Agency dashboard & billing', 'Team permissions per workspace'],
  },
  restaurants: {
    layout: 'local-business',
    meta: { title: 'LeadForGrow for Restaurants', description: 'Capture reservations, catering enquiries, and delivery orders.' },
    overline: 'Restaurants',
    headline: 'Never miss a reservation enquiry again.',
    subheadline: 'WhatsApp is how customers book. Automate confirmations, reminders, and feedback requests.',
    features: ['WhatsApp booking confirmations', 'Catering enquiry follow-up', 'Review request automations'],
  },
  'real-estate': {
    layout: 'property-cards',
    meta: { title: 'LeadForGrow for Real Estate', description: 'Qualify property enquiries and nurture buyers automatically.' },
    overline: 'Real Estate',
    headline: 'Qualify buyers while you\'re showing properties.',
    subheadline: 'Instant WhatsApp response, site visit scheduling, and long-cycle nurture for property sales.',
    features: ['Meta lead ad integration', 'Site visit reminders', 'Buyer qualification workflows'],
  },
  healthcare: {
    layout: 'trust-clinical',
    meta: { title: 'LeadForGrow for Healthcare', description: 'Appointment booking and patient follow-up with compliance in mind.' },
    overline: 'Healthcare',
    headline: 'Patient enquiries handled with care.',
    subheadline: 'Appointment reminders, follow-up sequences, and secure communication — built for clinics and healthcare providers.',
    features: ['Appointment confirmation via WhatsApp', 'Post-visit follow-up', 'HIPAA-aware data handling architecture'],
  },
  education: {
    layout: 'student-journey',
    meta: { title: 'LeadForGrow for Education', description: 'Admissions enquiry management and student nurture.' },
    overline: 'Education',
    headline: 'Convert admission enquiries into enrolled students.',
    subheadline: 'From form submission to counselling call to enrollment — automated at every step.',
    features: ['Admission form integration', 'Counsellor assignment', 'Demo class reminders'],
  },
  enterprise: {
    layout: 'enterprise-dark',
    meta: { title: 'LeadForGrow Enterprise', description: 'Security, SSO, and dedicated support for large teams.' },
    overline: 'Enterprise',
    headline: 'Enterprise-grade revenue infrastructure.',
    subheadline: 'SSO, audit logs, dedicated support, custom SLAs, and deployment options for regulated industries.',
    features: ['SSO & SAML (architecture ready)', 'Dedicated account manager', 'Custom integrations & API limits', '99.9% uptime SLA target'],
  },
};
