export const INTEGRATION_CATEGORIES = [
  { id: 'all', label: 'All integrations' },
  { id: 'communication', label: 'Communication' },
  { id: 'marketing', label: 'Marketing' },
  { id: 'payments', label: 'Payments' },
  { id: 'ecommerce', label: 'E-commerce' },
  { id: 'automation', label: 'Automation' },
  { id: 'meetings', label: 'Meeting Tools' },
  { id: 'crm-imports', label: 'CRM Imports' }
];

export const INTEGRATIONS = [
  {
    id: 'whatsapp-cloud',
    name: 'WhatsApp Cloud API',
    category: 'communication',
    description: 'Official Meta WhatsApp Business API for automated messaging and lead recovery.',
    color: 'emerald',
    initials: 'WA',
    connected: true,
    health: 'healthy',
    lastSynced: '2 min ago',
    account: 'LeadForGrow Business (+91 98765 43210)',
    permissions: ['Send messages', 'Receive webhooks', 'Manage templates'],
    features: ['Two-way chat', 'Template messages', 'Media support']
  },
  {
    id: 'interakt',
    name: 'Interakt',
    category: 'communication',
    description: 'WhatsApp marketing and support platform for Indian businesses.',
    color: 'violet',
    initials: 'IN',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Send campaigns', 'Sync contacts'],
    features: ['Broadcasts', 'Chatbot flows', 'CRM sync']
  },
  {
    id: 'twilio',
    name: 'Twilio',
    category: 'communication',
    description: 'SMS, voice, and WhatsApp messaging via Twilio APIs.',
    color: 'red',
    initials: 'TW',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Send SMS', 'Make calls'],
    features: ['SMS alerts', 'Voice IVR', 'WhatsApp fallback']
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'communication',
    description: 'Sync email conversations and send follow-ups from Gmail.',
    color: 'rose',
    initials: 'GM',
    connected: true,
    health: 'healthy',
    lastSynced: '15 min ago',
    account: 'sales@leadforgrow.com',
    permissions: ['Read mail', 'Send mail', 'Sync threads'],
    features: ['Email tracking', 'Thread sync', 'Templates']
  },
  {
    id: 'outlook',
    name: 'Outlook',
    category: 'communication',
    description: 'Microsoft 365 email integration for enterprise teams.',
    color: 'blue',
    initials: 'OL',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read mail', 'Send mail'],
    features: ['Calendar sync', 'Shared mailboxes']
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    description: 'Get lead alerts and task notifications in Slack channels.',
    color: 'purple',
    initials: 'SL',
    connected: true,
    health: 'warning',
    lastSynced: '1 hr ago',
    account: 'LeadForGrow Workspace',
    permissions: ['Post messages', 'Read channels'],
    features: ['Lead alerts', 'Task reminders', 'Daily digest']
  },
  {
    id: 'zoom',
    name: 'Zoom',
    category: 'communication',
    description: 'Schedule and log Zoom meetings from lead records.',
    color: 'blue',
    initials: 'ZM',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Create meetings', 'Read recordings'],
    features: ['One-click meetings', 'Call logging']
  },
  {
    id: 'meta-ads',
    name: 'Meta Ads',
    category: 'marketing',
    description: 'Import leads from Facebook and Instagram Lead Ads.',
    color: 'blue',
    initials: 'FB',
    connected: true,
    health: 'healthy',
    lastSynced: '5 min ago',
    account: 'LeadForGrow Ads Account',
    permissions: ['Read leads', 'Webhook events'],
    features: ['Lead form sync', 'Campaign attribution']
  },
  {
    id: 'google-ads',
    name: 'Google Ads',
    category: 'marketing',
    description: 'Capture leads from Google Ads lead form extensions.',
    color: 'amber',
    initials: 'GA',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read conversions', 'Import leads'],
    features: ['Offline conversions', 'Lead import']
  },
  {
    id: 'linkedin-ads',
    name: 'LinkedIn Ads',
    category: 'marketing',
    description: 'Sync B2B leads from LinkedIn Lead Gen Forms.',
    color: 'blue',
    initials: 'LI',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read leads'],
    features: ['Lead gen forms', 'Company enrichment']
  },
  {
    id: 'tiktok-ads',
    name: 'TikTok Ads',
    category: 'marketing',
    description: 'Import leads from TikTok Lead Generation campaigns.',
    color: 'slate',
    initials: 'TT',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read leads'],
    features: ['Instant forms', 'Audience sync']
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    category: 'payments',
    description: 'Track payments and link transactions to deals.',
    color: 'blue',
    initials: 'RZ',
    connected: true,
    health: 'healthy',
    lastSynced: '30 min ago',
    account: 'LeadForGrow Pvt Ltd',
    permissions: ['Read payments', 'Create payment links'],
    features: ['Payment links', 'Deal sync', 'Invoices']
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'payments',
    description: 'Global payment processing and subscription billing.',
    color: 'indigo',
    initials: 'ST',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read charges', 'Manage subscriptions'],
    features: ['Checkout links', 'Revenue tracking']
  },
  {
    id: 'paypal',
    name: 'PayPal',
    category: 'payments',
    description: 'Accept PayPal payments and sync to CRM deals.',
    color: 'blue',
    initials: 'PP',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read transactions'],
    features: ['Payment tracking']
  },
  {
    id: 'shopify',
    name: 'Shopify',
    category: 'ecommerce',
    description: 'Sync customers, orders, and abandoned carts as leads.',
    color: 'emerald',
    initials: 'SH',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read orders', 'Read customers'],
    features: ['Cart recovery', 'Order sync']
  },
  {
    id: 'woocommerce',
    name: 'WooCommerce',
    category: 'ecommerce',
    description: 'WordPress e-commerce integration for order-based leads.',
    color: 'purple',
    initials: 'WC',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read orders'],
    features: ['Order webhooks', 'Customer sync']
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'automation',
    description: 'Connect LeadForGrow to 5,000+ apps with no-code workflows.',
    color: 'orange',
    initials: 'ZP',
    connected: true,
    health: 'healthy',
    lastSynced: '10 min ago',
    account: '3 active Zaps',
    permissions: ['Triggers', 'Actions'],
    features: ['Custom workflows', 'Multi-step Zaps']
  },
  {
    id: 'pabbly',
    name: 'Pabbly Connect',
    category: 'automation',
    description: 'Affordable automation platform for Indian SMBs.',
    color: 'green',
    initials: 'PB',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Triggers', 'Actions'],
    features: ['Unlimited workflows']
  },
  {
    id: 'make',
    name: 'Make.com',
    category: 'automation',
    description: 'Visual automation builder for complex integrations.',
    color: 'violet',
    initials: 'MK',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Triggers', 'Actions'],
    features: ['Visual scenarios', 'Error handling']
  },
  {
    id: 'webhooks',
    name: 'Webhooks',
    category: 'automation',
    description: 'Send and receive real-time events to custom endpoints.',
    color: 'slate',
    initials: 'WH',
    connected: true,
    health: 'healthy',
    lastSynced: 'Just now',
    account: '2 active endpoints',
    permissions: ['Outbound events', 'Inbound payloads'],
    features: ['Custom payloads', 'Retry logic', 'Event logs']
  },
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'meetings',
    description: 'Auto-create leads when prospects book meetings.',
    color: 'blue',
    initials: 'CL',
    connected: true,
    health: 'healthy',
    lastSynced: '20 min ago',
    account: 'sales@leadforgrow.com',
    permissions: ['Read events', 'Create bookings'],
    features: ['Meeting sync', 'Lead creation']
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    category: 'meetings',
    description: 'Sync tasks and meetings with Google Calendar.',
    color: 'amber',
    initials: 'GC',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read events', 'Create events'],
    features: ['Two-way sync', 'Reminders']
  },
  {
    id: 'hubspot-import',
    name: 'HubSpot Import',
    category: 'crm-imports',
    description: 'Migrate contacts, deals, and activities from HubSpot.',
    color: 'orange',
    initials: 'HS',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read contacts', 'Read deals'],
    features: ['Bulk import', 'Field mapping']
  },
  {
    id: 'zoho-import',
    name: 'Zoho CRM Import',
    category: 'crm-imports',
    description: 'Import leads and pipelines from Zoho CRM.',
    color: 'red',
    initials: 'ZO',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read modules'],
    features: ['Module mapping', 'Incremental sync']
  },
  {
    id: 'salesforce-import',
    name: 'Salesforce Import',
    category: 'crm-imports',
    description: 'Enterprise migration from Salesforce CRM.',
    color: 'blue',
    initials: 'SF',
    connected: false,
    health: 'disconnected',
    lastSynced: null,
    permissions: ['Read objects'],
    features: ['Object mapping', 'Sandbox support']
  }
];

export const COLOR_MAP = {
  emerald: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-400',
  violet: 'bg-violet-100 text-violet-700 dark:bg-violet-950/50 dark:text-violet-400',
  red: 'bg-red-100 text-red-700 dark:bg-red-950/50 dark:text-red-400',
  rose: 'bg-rose-100 text-rose-700 dark:bg-rose-950/50 dark:text-rose-400',
  blue: 'bg-blue-100 text-blue-700 dark:bg-blue-950/50 dark:text-blue-400',
  purple: 'bg-purple-100 text-purple-700 dark:bg-purple-950/50 dark:text-purple-400',
  amber: 'bg-amber-100 text-amber-700 dark:bg-amber-950/50 dark:text-amber-400',
  slate: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
  indigo: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-400',
  orange: 'bg-orange-100 text-orange-700 dark:bg-orange-950/50 dark:text-orange-400',
  green: 'bg-green-100 text-green-700 dark:bg-green-950/50 dark:text-green-400'
};

export const HEALTH_STYLES = {
  healthy: { label: 'Healthy', dot: 'bg-emerald-500', text: 'text-emerald-700 dark:text-emerald-400', bg: 'bg-emerald-50 dark:bg-emerald-950/30' },
  warning: { label: 'Needs attention', dot: 'bg-amber-500', text: 'text-amber-700 dark:text-amber-400', bg: 'bg-amber-50 dark:bg-amber-950/30' },
  error: { label: 'Error', dot: 'bg-red-500', text: 'text-red-700 dark:text-red-400', bg: 'bg-red-50 dark:bg-red-950/30' },
  disconnected: { label: 'Not connected', dot: 'bg-slate-400', text: 'text-slate-500 dark:text-slate-400', bg: 'bg-slate-50 dark:bg-slate-800/50' }
};
