/**
 * Help Center content.
 *
 * Each step can specify:
 *   icon    — key from StepVisuals.ICON_MAP (topic-specific Lucide or brand icon)
 *   tone    — 'blue' | 'emerald' | 'amber' | 'violet' | 'rose' | 'slate' (colour of the step icon plate)
 *   visual  — optional inline UI mockup { kind, data } — see StepVisuals.jsx for supported kinds
 *
 * `brandIcon` on the guide itself renders in the hero chip (real WhatsApp /
 * Instagram / Gmail mark instead of the generic category icon).
 */

export const HELP_CATEGORIES = [
  { id: 'get-started',   label: 'Get started',      emoji: '🚀' },
  { id: 'communication', label: 'Communication',    emoji: '💬' },
  { id: 'automation',    label: 'Automation',       emoji: '⚡' },
  { id: 'commerce',      label: 'Bills & payments', emoji: '💳' },
  { id: 'settings',      label: 'Settings',         emoji: '⚙️' },
];

export const HELP_GUIDES = [
  // ── GET STARTED ──────────────────────────────────────────────────────
  {
    slug: 'getting-started',
    title: 'Getting started — your first 10 minutes',
    summary: 'The fastest path from signup to sending your first WhatsApp message.',
    category: 'get-started',
    time: '10 min',
    prereqs: [
      'A LeadForGrow account (sign up at /register)',
      'Meta Business Manager account with an approved WhatsApp Business number',
    ],
    steps: [
      { title: 'Sign in and land on the dashboard',
        body: 'You should see Dashboard with placeholders for Leads, Deals, Tasks. Nothing to configure yet.',
        icon: 'dashboard', tone: 'blue',
        visual: { kind: 'nav', data: { item: 'Dashboard', icon: 'dashboard', description: 'default landing' } } },
      { title: 'Connect WhatsApp',
        body: 'Left nav → Settings → Integrations → WhatsApp. Paste your Meta credentials (see the "Connect WhatsApp" guide for exact fields).',
        icon: 'whatsapp', tone: 'emerald',
        visual: { kind: 'nav', data: { item: 'Settings → Integrations → WhatsApp', icon: 'whatsapp' } } },
      { title: 'Set your bill header',
        body: 'Settings → Bill Header. Upload your logo + fill in business name, phone, email, address, GSTIN. This shows on every bill you send later.',
        icon: 'receipt', tone: 'violet',
        visual: { kind: 'checklist', data: { steps: [
          { label: 'Logo uploaded', done: true },
          { label: 'Business name', done: true },
          { label: 'Phone + email', done: true },
          { label: 'Address', done: false },
        ] } } },
      { title: 'Send your first message from the Inbox',
        body: 'Inbox → pick any existing WhatsApp conversation → type a reply → Send. If nothing appears, ask a customer to message your business number first.',
        icon: 'send', tone: 'emerald',
        visual: { kind: 'whatsapp', data: { direction: 'out', text: 'Hi — thanks for messaging us!', tail: '10:24' } } },
      { title: 'Create your first template',
        body: 'WhatsApp Templates → New template. Meta must approve every template before you can use it in a broadcast. See the "Create a Template" guide.',
        icon: 'file', tone: 'amber' },
      { title: 'Build a sequence for auto follow-ups',
        body: 'Sequences → New sequence → pick your industry template (e.g. Auto service · Post-visit 3-touch). Edit messages in Simple Edit → Activate.',
        icon: 'branch', tone: 'blue' },
    ],
    tips: [
      'You do not need to build everything before going live. Connect WhatsApp + send one bill via the Inbox — that alone replaces 3 tools.',
      'Use the /help pages any time — they are always available from the left nav.',
    ],
    related: ['connect-whatsapp', 'inbox-basics', 'create-template'],
  },

  // ── COMMUNICATION ────────────────────────────────────────────────────
  {
    slug: 'connect-whatsapp',
    title: 'Connect your WhatsApp Business account',
    summary: 'Paste your Meta Cloud API credentials into LFG so it can send and receive messages on your behalf.',
    category: 'communication',
    brandIcon: 'whatsapp',
    time: '15 min',
    prereqs: [
      'Meta Business Manager account (business.facebook.com)',
      'A WhatsApp Business Account (WABA) with a registered phone number',
      'A Meta App configured for WhatsApp Business Platform',
    ],
    steps: [
      { title: 'Open Meta for Developers',
        body: 'Go to developers.facebook.com → your app → WhatsApp → API Setup.',
        icon: 'globe', tone: 'blue',
        visual: { kind: 'browser', data: { url: 'developers.facebook.com/apps/…/whatsapp-business/wa-dev-console/' } } },
      { title: 'Copy 4 things from Meta',
        body: 'Phone number ID, WhatsApp Business Account ID, App ID, and a Permanent Access Token (System User token — not the temporary 24h one).',
        icon: 'copy', tone: 'amber',
        visual: { kind: 'form', data: { fields: [
          { label: 'Phone number ID', value: '4123456789012345' },
          { label: 'WhatsApp Business Account ID', value: '2345678901234567' },
          { label: 'App ID', value: '1234567890123456' },
          { label: 'Permanent Access Token', placeholder: 'EAA… (never expires)' },
        ] } } },
      { title: 'Paste into LFG',
        body: 'LeadForGrow → Settings → Integrations → WhatsApp. Fill Phone Number ID, Business Account ID, App ID, Access Token. Save.',
        icon: 'key', tone: 'violet',
        visual: { kind: 'nav', data: { item: 'Settings → Integrations → WhatsApp', icon: 'whatsapp' } } },
      { title: 'Set the webhook',
        body: 'In Meta Dashboard → WhatsApp → Configuration → Webhooks: set Callback URL to https://leadforgrow.com/api/webhooks/meta/[your-business-id], Verify Token to the value LFG shows in the Integrations page. Subscribe to fields: messages, message_template_status_update.',
        icon: 'webhook', tone: 'rose',
        visual: { kind: 'form', data: { fields: [
          { label: 'Callback URL', value: 'https://leadforgrow.com/api/webhooks/meta/[your-business-id]' },
          { label: 'Verify Token', placeholder: 'paste from LFG Integrations page' },
        ] } } },
      { title: 'Send yourself a test message',
        body: 'From your personal WhatsApp, message your business number. Open LFG Inbox — the conversation should appear within seconds.',
        icon: 'whatsapp', tone: 'emerald',
        visual: { kind: 'whatsapp', data: { direction: 'in', text: 'Testing 1 2 3', tail: '10:24' } } },
    ],
    tips: [
      'Never use a temporary 24-hour token. It stops working overnight and every send silently fails.',
      'If you already had another platform (Wati / AiSensy) connected, disconnect it from Meta first — one WABA can only send from one integration.',
    ],
    commonIssues: [
      { problem: 'Messages send but never appear in LFG Inbox', fix: 'Webhook is not subscribed to the "messages" field. Re-open Meta Configuration → Webhooks → Manage → tick the messages field.' },
      { problem: 'Error 190 "Session has expired"', fix: 'Access token is temporary. Generate a Permanent System User Token in Meta Business Settings and re-paste.' },
      { problem: 'Error #131047 on send', fix: 'You are outside the 24h customer service window. Ask the recipient to message you first, or use an approved template.' },
    ],
    related: ['inbox-basics', 'create-template'],
  },

  {
    slug: 'inbox-basics',
    title: 'Using the Inbox (WhatsApp, Instagram, Email)',
    summary: 'One unified inbox for all three channels. Reply, assign, tag, and jump between chats without switching apps.',
    category: 'communication',
    brandIcon: 'cluster',
    time: '5 min',
    prereqs: ['At least one channel connected (WhatsApp / Instagram / Email)'],
    steps: [
      { title: 'Open the Inbox',
        body: 'Left nav → Inbox. Left panel lists all conversations across channels — filter by channel or status at the top.',
        icon: 'message', tone: 'emerald',
        visual: { kind: 'nav', data: { item: 'Inbox', icon: 'message', description: 'Unified' } } },
      { title: 'Understand the icons',
        body: 'Green stripe = unread. Left arrow = incoming. Right arrow = outgoing. Tick = sent. Double tick = delivered. Blue double tick = read.',
        icon: 'list', tone: 'blue' },
      { title: 'Reply to a customer',
        body: 'Click any conversation → type in the box at the bottom → Enter. Works inside the 24h window on WhatsApp.',
        icon: 'send', tone: 'emerald',
        visual: { kind: 'whatsapp', data: { direction: 'out', text: 'Sure, we can do that. When would you like to come in?', tail: '11:02' } } },
      { title: 'When the 24h window is closed',
        body: 'LFG auto-swaps the reply box for a template picker. Choose an approved template, fill in variables, hit Send.',
        icon: 'timer', tone: 'amber' },
      { title: 'Customer profile on the right',
        body: 'Every chat shows lead info, pipeline stage, follow-up date, and quick actions like Create Bill.',
        icon: 'users', tone: 'violet' },
    ],
    tips: [
      'Assign chats to teammates from the customer profile panel — that person then owns the follow-up.',
      'Add labels (Hot, VIP, Follow-up) to slice the inbox by attention level.',
    ],
    related: ['create-template', 'create-bill'],
  },

  {
    slug: 'create-template',
    title: 'Create and submit a WhatsApp template',
    summary: 'Templates let you initiate conversations outside the 24-hour window. Meta must approve each one.',
    category: 'communication',
    brandIcon: 'whatsapp',
    time: '10 min + Meta approval wait',
    prereqs: ['WhatsApp connected'],
    steps: [
      { title: 'Open the template builder',
        body: 'Left nav → WhatsApp Templates → + New template.',
        icon: 'file', tone: 'emerald',
        visual: { kind: 'nav', data: { item: 'WhatsApp Templates → New template', icon: 'file' } } },
      { title: 'Fill in basics',
        body: 'Name (lowercase, underscores only), Category (Marketing / Utility / Authentication), Language.',
        icon: 'settings', tone: 'blue',
        visual: { kind: 'form', data: { fields: [
          { label: 'Name', value: 'bill_delivery' },
          { label: 'Category', value: 'UTILITY' },
          { label: 'Language', value: 'English (en_US)' },
        ] } } },
      { title: 'Pick a header',
        body: 'Optional. Can be text or media (image / video / document). If media, upload a sample — Meta needs it to review the shape.',
        icon: 'image', tone: 'violet' },
      { title: 'Write the body',
        body: 'Up to 1024 characters. Use {{1}}, {{2}}, etc. for variables. Provide sample values for each so Meta reviewers see it in context.',
        icon: 'message', tone: 'emerald',
        visual: { kind: 'whatsapp', data: { direction: 'out', text: 'Hi {{1}},\n\nYour bill from {{2}} is ready.\n\nBill number: {{3}}\nTotal amount: ₹{{4}}', tail: 'sample' } } },
      { title: 'Optional footer + buttons',
        body: 'Footer is a small tagline. Buttons can be Quick Reply, URL (with a variable if you want), or Call.',
        icon: 'link', tone: 'amber' },
      { title: 'Submit for approval',
        body: 'Meta approves in 20 minutes to 24 hours for most Utility templates, longer for Marketing.',
        icon: 'shield', tone: 'blue',
        visual: { kind: 'button', data: { label: 'Submit for approval', kind: 'primary', icon: 'shield' } } },
    ],
    tips: [
      'Utility templates are ~7x cheaper than Marketing and approve faster. Use Utility for anything transactional (order confirmations, appointment reminders, bill delivery).',
      'Do not put URLs or aggressive discounts in Marketing templates — Meta rejects them.',
      'Once approved, the same template works for every future send. You do not re-approve per use.',
    ],
    commonIssues: [
      { problem: 'Template rejected — "generic content"', fix: 'Add more specific context. Meta rejects vague copy like "Special offer!" — say what the offer actually is.' },
      { problem: 'Template stuck in PENDING for 24h+', fix: 'Rare. Contact Meta support via Business Manager, or resubmit with clearer variable samples.' },
    ],
    related: ['send-broadcast', 'create-bill'],
  },

  {
    slug: 'send-broadcast',
    title: 'Send a WhatsApp broadcast',
    summary: 'Blast an approved template to many leads at once, with per-recipient personalization and delivery tracking.',
    category: 'communication',
    brandIcon: 'whatsapp',
    time: '10 min',
    prereqs: ['WhatsApp connected', 'At least one APPROVED template', 'A list of leads or a CSV to import'],
    steps: [
      { title: 'Open Broadcasts',
        body: 'Left nav → Broadcasts → + New broadcast.',
        icon: 'send', tone: 'emerald',
        visual: { kind: 'nav', data: { item: 'Broadcasts → New broadcast', icon: 'send' } } },
      { title: 'Pick your template',
        body: 'Choose an approved template from the dropdown. LFG shows a live preview on the right.',
        icon: 'file', tone: 'blue' },
      { title: 'Choose your audience',
        body: 'Four modes: pick leads by tag, upload a CSV, filter by status/pipeline, or pick specific leads. Live count updates as you refine.',
        icon: 'users', tone: 'violet',
        visual: { kind: 'checklist', data: { steps: [
          { label: 'By tag', done: true },
          { label: 'CSV upload', done: false },
          { label: 'Filter', done: false },
          { label: 'Pick manually', done: false },
        ] } } },
      { title: 'Map variables',
        body: 'For each {{1}}, {{2}} in your template, pick a lead field (name, phone, custom) or type a static value. Preview shows what the first recipient will see.',
        icon: 'hash', tone: 'amber' },
      { title: 'Turn on the engagement filter (recommended)',
        body: 'Only sends to leads who messaged you in the last 30 days. Massively improves delivery rate and protects your Meta quality score.',
        icon: 'filter', tone: 'emerald' },
      { title: 'Check the quality banner',
        body: 'The pre-send banner shows your current WhatsApp phone number quality rating (Green / Yellow / Red). If Yellow/Red, wait a few days or use a smaller batch.',
        icon: 'shield', tone: 'blue' },
      { title: 'Send',
        body: 'LFG sends at ~2.5 messages/second with a 400ms throttle. If quality drops >20%, the broadcast auto-pauses.',
        icon: 'send', tone: 'rose',
        visual: { kind: 'button', data: { label: 'Send broadcast', kind: 'primary', icon: 'send' } } },
    ],
    tips: [
      'First broadcast to a new list: keep it under 20 recipients. Watch delivery — if 90%+ land, ramp up.',
      'Never broadcast to a list you have not messaged in 60+ days. Meta silently drops those and your quality tanks.',
    ],
    commonIssues: [
      { problem: 'Broadcast shows "Sent" but many messages "not delivered"', fix: 'Usually Meta quality-based filtering. Check phone number quality in Meta Business → WhatsApp Manager → Phone Numbers.' },
      { problem: 'Error #131049 for many recipients', fix: 'Meta silently dropping for engagement. Turn on the engagement filter and try again.' },
    ],
    related: ['create-template', 'sequences'],
  },

  // ── AUTOMATION ───────────────────────────────────────────────────────
  {
    slug: 'sequences',
    title: 'Build a follow-up sequence (drip automation)',
    summary: 'Multi-touch automatic follow-ups. Day 1, Day 3, Day 7 — reacts to customer replies.',
    category: 'automation',
    time: '10 min',
    prereqs: ['WhatsApp connected', 'Approved templates for each step (or use text messages inside the 24h window)'],
    steps: [
      { title: 'Open Sequences',
        body: 'Left nav → Sequences → + Create sequence.',
        icon: 'branch', tone: 'blue',
        visual: { kind: 'nav', data: { item: 'Sequences → Create sequence', icon: 'branch' } } },
      { title: 'Pick an industry template',
        body: 'Step 2 of the wizard shows pre-built sequences by industry (Auto service, Salon, E-commerce, etc.). Click any to preview.',
        icon: 'list', tone: 'amber' },
      { title: 'Preview + Use',
        body: 'The preview modal shows every step with delay + message. Note the smart-branching badges (🎯 Goal / ⏸ Pauses if replied / 🛑 Exits on STOP). Click "Use this template".',
        icon: 'sparkles', tone: 'violet',
        visual: { kind: 'button', data: { label: 'Use this template', kind: 'primary', icon: 'arrow' } } },
      { title: 'Edit messages in Simple Edit',
        body: 'The default view is Simple Edit — a list of cards, one per step. Change wording, delay days, or channel per step. Add or delete steps.',
        icon: 'palette', tone: 'emerald' },
      { title: 'Set the trigger',
        body: 'Trigger & A/B tab → pick what enrolls a lead: new lead created, tag added, no reply, stage changed, etc.',
        icon: 'zap', tone: 'amber' },
      { title: 'Activate',
        body: 'Save draft → Activate. From that moment, matching leads enter the sequence automatically.',
        icon: 'play', tone: 'emerald',
        visual: { kind: 'button', data: { label: '▶ Activate', kind: 'primary', icon: 'play' } } },
    ],
    tips: [
      'Test with fractional delays (0.001 days ≈ 1.4 min) to see all 3 steps play out in 5 minutes. Change to real values (1, 3, 7) before going live.',
      'Smart branching is what beats every competitor: the sequence stops the moment the customer replies, opts out, or clicks your goal button.',
    ],
    commonIssues: [
      { problem: 'Sequence never fires', fix: 'Cron worker not running. Check Vercel → Cron Jobs or hit /api/cron/automation-schedules manually.' },
      { problem: 'Step fires but message stuck at "Sent"', fix: 'Same quality issue as broadcasts. Check quality rating in Meta.' },
    ],
    related: ['create-template', 'automation-rules'],
  },

  {
    slug: 'automation-rules',
    title: 'Set up an Automation Rule (auto-reply to new leads)',
    summary: 'Send an instant WhatsApp / email to every new lead the moment they land in LFG.',
    category: 'automation',
    time: '5 min',
    prereqs: ['WhatsApp or email connected'],
    steps: [
      { title: 'Open Automation Rules',
        body: 'Left nav → Automation Rules → + Create rule.',
        icon: 'zap', tone: 'amber',
        visual: { kind: 'nav', data: { item: 'Automation Rules → Create rule', icon: 'zap' } } },
      { title: 'Pick a trigger',
        body: 'e.g. "When a new lead is created" or "When lead status changes to Contacted".',
        icon: 'tag', tone: 'blue' },
      { title: 'Pick an action',
        body: 'Send WhatsApp / Send email / Assign to agent / Add tag / Create task. Multiple actions can chain.',
        icon: 'arrow', tone: 'emerald' },
      { title: 'Choose your template',
        body: 'For WhatsApp: pick an approved template. For email: pick or write copy.',
        icon: 'file', tone: 'violet' },
      { title: 'Enable and save',
        body: 'Toggle enabled → Save. Fires immediately on the next matching event.',
        icon: 'play', tone: 'emerald' },
    ],
    tips: [
      'Combine with Sequences: rule sends the instant "thanks for enquiring" message, then a Sequence handles Day 3 and Day 7 follow-ups.',
    ],
    related: ['sequences', 'create-template'],
  },

  // ── COMMERCE ─────────────────────────────────────────────────────────
  {
    slug: 'create-bill',
    title: 'Create a bill and send it via WhatsApp',
    summary: 'Professional PDF bill with your logo, sent to the customer on WhatsApp in one click.',
    category: 'commerce',
    time: '3 min per bill',
    prereqs: ['Bill Header set up (Settings → Bill Header)', 'WhatsApp connected'],
    steps: [
      { title: 'Set up your Bill Header (once)',
        body: 'Settings → Bill Header. Upload your logo, fill in business name, phone, email, address, GSTIN. Save. This appears on every bill.',
        icon: 'image', tone: 'violet',
        visual: { kind: 'nav', data: { item: 'Settings → Bill Header', icon: 'receipt' } } },
      { title: 'Create a bill',
        body: 'Two ways: Left nav → Bills → + New bill. OR: From any chat, click "Create bill for this customer" in the right sidebar — auto-fills the customer info.',
        icon: 'receipt', tone: 'blue',
        visual: { kind: 'button', data: { label: '+ New bill', kind: 'primary', icon: 'receipt' } } },
      { title: 'Add line items',
        body: 'Description + Quantity + Rate. Add as many rows as you need. LFG auto-calculates subtotal.',
        icon: 'list', tone: 'amber',
        visual: { kind: 'form', data: { fields: [
          { label: 'Item 1', value: 'Sensor · Qty 1 · ₹2,400' },
          { label: 'Item 2', value: 'Scanning · Qty 1 · ₹550' },
          { label: 'Item 3', value: 'Labour · Qty 1 · ₹800' },
          { label: 'Subtotal', value: '₹3,750' },
        ] } } },
      { title: 'Adjust discount + tax (optional)',
        body: 'Discount is a flat rupee amount. Tax rate is a percentage. Totals recalculate live.',
        icon: 'hash', tone: 'emerald' },
      { title: 'Save & send',
        body: '"Save & send on WhatsApp" generates the PDF, uploads it to Cloudinary, and sends via WhatsApp. Customer gets the PDF within 10 seconds.',
        icon: 'whatsapp', tone: 'emerald',
        visual: { kind: 'bill-card', data: {
          title: 'PG-2026-001',
          subtitle: 'Total ₹3,400 · sent to Daksh on WhatsApp',
          actions: [{ label: 'Sent', kind: 'primary' }, { label: 'Download PDF', kind: 'outline' }],
        } } },
    ],
    tips: [
      'Inside the 24h window (customer messaged recently): sends instantly as a free-form document.',
      'Outside the window: LFG auto-falls-back to the "bill_delivery" template (must be approved by Meta once — you build it in WhatsApp Templates).',
      'Once sent, the bill is locked from editing. To fix, "Void" it and create a new draft.',
    ],
    commonIssues: [
      { problem: 'Send failed: "24h window closed"', fix: 'Build + submit the "bill_delivery" template — see the "Create Template" guide. Once approved, this stops happening.' },
      { problem: 'PDF has no logo', fix: 'Upload logo in Settings → Bill Header, then regenerate the bill (Bill detail → Download PDF to check).' },
    ],
    related: ['bill-header-setup', 'payment-link', 'create-template'],
  },

  {
    slug: 'bill-header-setup',
    title: 'Set up your Bill Header (one-time)',
    summary: 'Your logo, business name, phone, email, address, and GSTIN — used on every bill you ever send.',
    category: 'commerce',
    time: '5 min',
    prereqs: [],
    steps: [
      { title: 'Open Bill Header settings',
        body: 'Settings → Bill Header (or from any bill editor, click "Complete setup" in the top strip).',
        icon: 'receipt', tone: 'violet',
        visual: { kind: 'nav', data: { item: 'Settings → Bill Header', icon: 'receipt' } } },
      { title: 'Upload your logo',
        body: 'PNG / JPG / WebP, under 2 MB. Auto-resized to 400×400 for fast PDF loading. Appears top-left of every bill.',
        icon: 'image', tone: 'emerald' },
      { title: 'Fill in business info',
        body: 'Business name (required), website, phone, email, address (multi-line ok), GSTIN (optional — displays on the bill footer if provided).',
        icon: 'building', tone: 'blue',
        visual: { kind: 'form', data: { fields: [
          { label: 'Business name', placeholder: 'Your business name' },
          { label: 'Phone', placeholder: '+91 …' },
          { label: 'Email', placeholder: 'hello@yourbusiness.com' },
          { label: 'GSTIN (optional)', placeholder: '22AAAAA0000A1Z5' },
        ] } } },
      { title: 'Save',
        body: 'Every future bill uses these fields automatically. No re-entry per bill.',
        icon: 'check', tone: 'emerald',
        visual: { kind: 'toast', data: { text: 'Saved — will show on every bill' } } },
    ],
    tips: [
      'Your customer-facing docs show YOUR branding, not LeadForGrow branding. There is no LFG logo or watermark anywhere on the PDF.',
    ],
    related: ['create-bill'],
  },

  {
    slug: 'payment-link',
    title: 'Send a Razorpay payment link with a bill',
    summary: 'Customer taps a link, pays via UPI/card/wallet, money goes directly to your bank. LFG never holds funds.',
    category: 'commerce',
    time: '10 min setup + 30 sec per bill',
    prereqs: ['A Razorpay account (free signup at razorpay.com)'],
    steps: [
      { title: 'Create a Razorpay account',
        body: 'Sign up at razorpay.com — needs your PAN, GST (if applicable), bank details. Takes 5-10 min.',
        icon: 'globe', tone: 'blue',
        visual: { kind: 'browser', data: { url: 'dashboard.razorpay.com/signup' } } },
      { title: 'Generate API keys',
        body: 'Razorpay Dashboard → Settings → API Keys → Generate Key. Copy Key ID (rzp_live_… or rzp_test_…) and Key Secret. The secret is only shown once — save it now.',
        icon: 'key', tone: 'amber',
        visual: { kind: 'form', data: { fields: [
          { label: 'Key ID', value: 'rzp_live_XXXXXXXXXXXX' },
          { label: 'Key Secret', placeholder: 'shown only once — save now' },
        ] } } },
      { title: 'Connect in LFG',
        body: 'Open any bill → click "Connect Razorpay to send a payment link" → paste both keys → Save. LFG encrypts the secret at rest.',
        icon: 'card', tone: 'violet',
        visual: { kind: 'button', data: { label: 'Connect Razorpay', kind: 'primary', icon: 'card' } } },
      { title: '(Optional) Set up auto-mark-paid',
        body: 'Razorpay → Webhooks → Add webhook. URL: https://leadforgrow.com/api/webhooks/razorpay. Events: payment_link.paid, payment_link.expired, payment_link.cancelled. Add a secret string, paste that same string into LFG under Webhook Secret. Now paid bills auto-flip to "Paid" without manual clicks.',
        icon: 'webhook', tone: 'rose' },
      { title: 'Send a payment link',
        body: 'Bill detail → "Send payment link on WhatsApp". Customer receives a link, taps, pays. Money settles directly to your bank via Razorpay.',
        icon: 'link', tone: 'emerald',
        visual: { kind: 'payment-link', data: { business: 'Your Business', amount: '3,400', link: 'rzp.io/i/abc123' } } },
    ],
    tips: [
      'Razorpay charges 2% + GST per transaction. LFG takes zero cut.',
      'Use test keys (rzp_test_…) first. Test payments are free and use test cards.',
      'When the customer pays, they see YOUR business name on the Razorpay page, not LeadForGrow.',
    ],
    commonIssues: [
      { problem: '"Razorpay refused the link request"', fix: 'Usually invalid keys. Regenerate in Razorpay Dashboard and re-paste. Also check the account is "Live" not just "Activated for tests".' },
      { problem: 'Customer pays but bill stays "Sent"', fix: 'Webhook is not set up. Follow step 4 above, or click "Mark as paid" manually.' },
    ],
    related: ['create-bill'],
  },

  // ── SETTINGS ─────────────────────────────────────────────────────────
  {
    slug: 'team-management',
    title: 'Add teammates and set roles',
    summary: 'Invite agents to your workspace, assign them to leads, control who can see billing.',
    category: 'settings',
    time: '5 min',
    prereqs: ['You are the workspace owner or admin'],
    steps: [
      { title: 'Open Team settings',
        body: 'Settings → Team → + Invite teammate.',
        icon: 'users', tone: 'blue',
        visual: { kind: 'nav', data: { item: 'Settings → Team', icon: 'users' } } },
      { title: 'Enter their email and pick a role',
        body: 'Owner (full access), Admin (settings + team), Team Member (leads + inbox + bills), View Only.',
        icon: 'shield', tone: 'violet',
        visual: { kind: 'form', data: { fields: [
          { label: 'Teammate email', placeholder: 'teammate@yourbusiness.com' },
          { label: 'Role', value: 'Team Member' },
        ] } } },
      { title: 'Send invite',
        body: 'They receive an email with a signup link. Once they set a password, they see the workspace immediately.',
        icon: 'mail', tone: 'emerald' },
      { title: 'Assign leads and chats',
        body: 'From any lead or chat, click Assign → pick a teammate. That person becomes the owner and gets notifications.',
        icon: 'tag', tone: 'amber' },
    ],
    tips: [
      'For a 3-person shop: 1 Owner + 1 Admin + 1 Team Member is typical. Give View Only to accountants who only need reports.',
    ],
    related: [],
  },
];

export function getGuide(slug) {
  return HELP_GUIDES.find((g) => g.slug === slug) || null;
}

export function guidesByCategory(categoryId) {
  return HELP_GUIDES.filter((g) => g.category === categoryId);
}
